# Generated by Django 5.2.8 on 2025-11-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("fresher", "Fresher"),
                            ("junior", "Junior (0-2 years)"),
                            ("mid", "Mid-level (2-5 years)"),
                        ],
                        default="fresher",
                        max_length=20,
                    ),
                ),
                (
                    "career_track",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web_dev", "Web Development"),
                            ("data_science", "Data Science"),
                            ("mobile_dev", "Mobile Development"),
                            ("ui_ux", "UI/UX Design"),
                            ("marketing", "Digital Marketing"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_description", models.TextField(blank=True)),
                ("cv_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
