# Generated by Django 5.2.8 on 2025-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("required_skills", models.JSONField(default=list)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("fresher", "Fresher"),
                            ("junior", "Junior (0-2 years)"),
                            ("mid", "Mid-level (2-5 years)"),
                        ],
                        default="fresher",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("part_time", "Part-time"),
                            ("full_time", "Full-time"),
                            ("contract", "Contract"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("application_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
